version: "3"

volumes:
  bundle:

services:
  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./Backup:/root/Backup
      - ./backups/:/root/backups
    command: bash -c "bundle exec whenever --update-crontab && cron && touch /var/log/cron.log && tail -f /var/log/cron.log"
    stdin_open: true
    tty: true
    env_file: app.env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'
